### ISSUE TITLE
代码缺少platform.h文件

### ISSUE THREAD

**Issue by charliexp** [IronsDu/accumulation-dev#2]

**Comment by IronsDu** [comment]
你好，你是用的最新版么？我没发现问题。你用的windows还是linux？

**Comment by charliexp** [comment]
linux 版本的，git下来的，编译提示没有platform.h文件

**Comment by IronsDu** [comment]
不会有问题啊。你看看 accumulation-dev/src/net 目录里有没有 Platform.h？ (不是小写的platform.h)

**Comment by IronsDu** [comment]
另外，需要支持C++11的编译器哦。

**Comment by charliexp** [comment]
<img width="544" alt="2016-05-23 10 36 20" src="https://cloud.githubusercontent.com/assets/12693198/15474296/dce0193a-2136-11e6-9cb0-4204adb8ba80.png">
这里面是小写的

**Comment by IronsDu** [comment]
谢谢，已改。（确实忘记改成大写了，不过好奇怪，这个文件按理不会在出现在现在的Makefile里的，我这测试也没发现问题~~当然以后确实会遇到问题）
